# Generated by Django 5.0.7 on 2024-09-26 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=50)),
                ('description', models.CharField(db_column='desctiption', max_length=1000)),
            ],
            options={
                'db_table': 'campagne',
            },
        ),
        migrations.CreateModel(
            name='codeerreur',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('description_code', models.CharField(db_column='description_code', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Statutes',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('statutes', models.CharField(db_column='statutes', max_length=8)),
                ('changedate', models.DateField(auto_now_add=True, db_column='changeDate')),
                ('id_prospect', models.IntegerField(db_column='id_prospect')),
            ],
            options={
                'db_table': 'statutes',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Con',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=1000)),
                ('jouractivite', models.CharField(db_column='jouractivite', max_length=3)),
                ('heureactivite', models.CharField(db_column='heureactivite', max_length=5)),
                ('name', models.CharField(db_column='name', max_length=50)),
                ('linkedin_lien', models.CharField(db_column='linkedin_lien', max_length=200)),
                ('google_sheet', models.CharField(blank=True, db_column='google_sheet', max_length=300, null=True)),
                ('date_creation', models.DateField(blank=True, db_column='date_creation', null=True)),
                ('idcampagne', models.ForeignKey(db_column='idcampagne', on_delete=django.db.models.deletion.CASCADE, to='campagnes.campagne')),
                ('iduser', models.ForeignKey(db_column='iduser', on_delete=django.db.models.deletion.CASCADE, to='campagnes.users')),
            ],
            options={
                'db_table': 'con',
            },
        ),
        migrations.CreateModel(
            name='Erreur',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('etat', models.BooleanField(db_column='etat')),
                ('date_err', models.DateField(db_column='date_err')),
                ('code_err', models.IntegerField(db_column='code_err')),
                ('idcon', models.ForeignKey(db_column='id_con', on_delete=django.db.models.deletion.CASCADE, to='campagnes.con')),
            ],
            options={
                'db_table': 'erreur_con',
            },
        ),
        migrations.CreateModel(
            name='Fonctionement',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('type', models.CharField(db_column='type', max_length=7)),
                ('tempsprochaineexec', models.IntegerField(db_column='TempsProchaineExec')),
                ('statutes_activation', models.CharField(db_column='Statutes_activation', max_length=8)),
                ('idcampagne', models.ForeignKey(db_column='idcampagne', on_delete=django.db.models.deletion.CASCADE, to='campagnes.campagne')),
            ],
            options={
                'db_table': 'fonctionement',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('idcon', models.ForeignKey(db_column='idcon', on_delete=django.db.models.deletion.CASCADE, to='campagnes.con')),
            ],
            options={
                'db_table': 'manager',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('corp', models.CharField(db_column='corp', max_length=1500)),
                ('idcon', models.ForeignKey(db_column='idcon', on_delete=django.db.models.deletion.CASCADE, to='campagnes.con')),
                ('idfonc', models.ForeignKey(db_column='idfonc', on_delete=django.db.models.deletion.CASCADE, to='campagnes.fonctionement')),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='NomChamp',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nom', models.CharField(db_column='nom', max_length=50)),
                ('idcon', models.ForeignKey(db_column='idcon', on_delete=django.db.models.deletion.CASCADE, to='campagnes.con')),
            ],
            options={
                'db_table': 'nomchamp',
            },
        ),
        migrations.CreateModel(
            name='Prospects',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('linkedin_profile', models.CharField(db_column='linkedin_profile', max_length=100)),
                ('name', models.CharField(db_column='name', max_length=50)),
                ('idcon', models.ForeignKey(db_column='idcon', on_delete=django.db.models.deletion.CASCADE, to='campagnes.con')),
                ('statutes', models.ForeignKey(db_column='statutes', on_delete=django.db.models.deletion.CASCADE, to='campagnes.statutes')),
            ],
            options={
                'db_table': 'prospects',
            },
        ),
        migrations.CreateModel(
            name='TachesProgrammes',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('heure', models.DateTimeField(db_column='heure')),
                ('idcon', models.ForeignKey(db_column='idcon', on_delete=django.db.models.deletion.CASCADE, to='campagnes.con')),
            ],
            options={
                'db_table': 'tachesprogrammes',
            },
        ),
        migrations.AddField(
            model_name='campagne',
            name='iduser',
            field=models.ForeignKey(db_column='iduser', on_delete=django.db.models.deletion.CASCADE, to='campagnes.users'),
        ),
        migrations.CreateModel(
            name='ValeurChamp',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('valeur', models.CharField(db_column='valeur', max_length=300)),
                ('id_champ', models.ForeignKey(db_column='id_champ', on_delete=django.db.models.deletion.CASCADE, to='campagnes.nomchamp')),
                ('id_prospect', models.ForeignKey(db_column='id_prospect', on_delete=django.db.models.deletion.CASCADE, to='campagnes.prospects')),
            ],
            options={
                'db_table': 'valeurchamp',
            },
        ),
    ]
