# Generated by Django 5.0.7 on 2024-11-04 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagnes', '0002_alter_codeerreur_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagne',
            name='description',
            field=models.CharField(db_column='description', max_length=1000),
        ),
        migrations.AlterField(
            model_name='erreur',
            name='code_err',
            field=models.ForeignKey(db_column='code_err', on_delete=django.db.models.deletion.CASCADE, to='campagnes.codeerreur'),
        ),
        migrations.AlterField(
            model_name='erreur',
            name='idcon',
            field=models.ForeignKey(db_column='idcon', on_delete=django.db.models.deletion.CASCADE, to='campagnes.con'),
        ),
        migrations.AlterField(
            model_name='valeurchamp',
            name='id_champ',
            field=models.ForeignKey(db_column='idchamp', on_delete=django.db.models.deletion.CASCADE, to='campagnes.nomchamp'),
        ),
        migrations.AlterField(
            model_name='valeurchamp',
            name='id_prospect',
            field=models.ForeignKey(db_column='idprospect', on_delete=django.db.models.deletion.CASCADE, to='campagnes.prospects'),
        ),
        migrations.AlterModelTable(
            name='codeerreur',
            table='codeerreur',
        ),
    ]
