# Generated by Django 5.0.7 on 2024-11-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagnes', '0003_alter_campagne_description_alter_erreur_code_err_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statutes',
            name='id_prospect',
            field=models.IntegerField(blank=True, db_column='id_prospect', null=True),
        ),
    ]
