# Generated by Django 5.0.7 on 2024-11-19 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagnes', '0004_alter_statutes_id_prospect'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionErreur',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('action', models.CharField(db_column='action', max_length=300)),
            ],
            options={
                'db_table': 'actionerreur',
            },
        ),
        migrations.CreateModel(
            name='ListAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idaction', models.ForeignKey(db_column='idaction', on_delete=django.db.models.deletion.CASCADE, to='campagnes.actionerreur')),
                ('idcode', models.ForeignKey(db_column='idcode', on_delete=django.db.models.deletion.CASCADE, to='campagnes.codeerreur')),
            ],
            options={
                'db_table': 'listaction',
            },
        ),
        migrations.AddConstraint(
            model_name='listaction',
            constraint=models.UniqueConstraint(fields=('idcode', 'idaction'), name='unique_listaction'),
        ),
    ]
