# Generated by Django 5.0.7 on 2024-12-09 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagnes', '0005_actionerreur_listaction_listaction_unique_listaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatistiquesCampagne',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='date')),
                ('not_sent', models.IntegerField(db_column='not_sent')),
                ('on_hold', models.IntegerField(db_column='on_hold')),
                ('accepted', models.IntegerField(db_column='accepted')),
                ('success', models.IntegerField(db_column='success')),
                ('refused', models.IntegerField(db_column='refused')),
                ('message1st', models.IntegerField(db_column='message1st')),
                ('message2nd', models.IntegerField(db_column='message2nd')),
                ('message3rd', models.IntegerField(db_column='message3rd')),
                ('idcon', models.ForeignKey(db_column='idcon', on_delete=django.db.models.deletion.CASCADE, to='campagnes.con')),
            ],
        ),
    ]
