# Generated by Django 5.0.7 on 2024-12-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagnes', '0007_campagne_visibilite_alter_statistiquescampagne_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospects',
            name='complete_name',
            field=models.CharField(db_column='complete_name', default=None, max_length=200),
        ),
    ]
