# Generated by Django 5.0.7 on 2024-12-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagnes', '0009_con_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospects',
            name='complete_name',
            field=models.CharField(blank=True, db_column='complete_name', default=None, max_length=200, null=True),
        ),
    ]
